language: csharp
solution: sql-formatter.sln
mono:
  - 3.10.0
install:
  - nuget restore sql-formatter.sln
  - nuget install NUnit.Console -Version 3.12.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release sql-formatter.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe ./SqlFormatter.Tests/bin/Release/SqlFormatter.Tests.dll
